core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from webnews.views import index

urlpatterns = [
    path("admin/", admin.site. urls),
    path("", index, name="index"),
    path("webnews/", include("webnews.urls", namespace="webnews")),

]
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news_agency/urls.py
from django.contrib import admin
from django.urls import path, include

from webnews.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("webnews.urls")),
]

webnews/urls.py
from django.urls import path

from webnews.views import (
    index,
    NewspaperDetailView,
    RedactorListView,
)

urlpatterns = [
    path("123/", index),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
]
app_name = "webnews"

webnews/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> object:
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    context = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name="newspapers"
    )
    publishers = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="newspapers"
    )

    class Meta:
        ordering = ["-published_date"]

    def __str__(self):
        return (f"{self.title} "
                f"(published:{self.published_date}, "
                f"format: {self.topic.name})")

webnews/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.db.models import Count

from webnews.models import Newspaper, Redactor, Topic


def index(request):
    news_list = Newspaper.objects.all().select_related("topic")
    context = {
        "news_list": news_list,
    }
    return render(request, "webnews/index.html", context=context)


class NewspaperDetailView(generic.DetailView):
    model = Newspaper


class RedactorListView(generic.ListView):
    model = Redactor

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">

<head>

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">

<title>
  Soft UI Design System by Creative Tim
</title>
<!--     Fonts and icons     -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />

<!-- Nucleo Icons -->
<link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
<link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />

<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />

<!-- CSS Files -->
<link id="pagestyle" href="{% static 'css/soft-design-system.css' %}" rel="stylesheet" />
</head>

{#<body {% block body %}{% endblock body %})>#}
<body style="background-image: url('/static/img/curved-images/2.jpg'); background-size: cover;" {% block body %}{% endblock body %})>

  {% block header %}

    {% include 'includes/navigation.html' %}

  {% endblock header %}
<div class="container mt-7">
{% block content %}{% endblock content %}
  </div>


  {% block footer %}

    {% include 'includes/footer_background.html' %}

  {% endblock footer %}

  {% include 'includes/scripts.html' %}

</body>
</html>

templates/includes/footer_background.html
{% block javascripts %}{% endblock javascripts %}
    <div class="position-absolute w-100 z-index-0 bottom-11 ">
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
        </defs>
        <g class="moving-waves">
          <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(105,100,55,0.40" />
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(0,0,0,0.35)" />
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(117,16,33,0.25)" />
          <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
          <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
        </g>
      </svg>
    </div>

templates/includes/news.html
{% for news in news_list %}
  <section class="pt-1">
    <div class="container">
      <div class="row">
        <div
            class="col-lg-10 z-index-2 border-radius-xl mt-2 mx-auto py-3 blur shadow-blur">

            <li style="text-align: left" class="mt-4">
              <strong>
                <a href="#">{{ news.title }}</a>
              </strong>
              <hr>
              {{ news.context }}
            </li>
          <p style="text-align: right" class="mt-0 text-black-50">
            {{ news.published_date }}
          </p>
          <p style="text-align: right" class="mt-0 mb-0 text-primary">
            <a href="#">Read more..</a>.
          </p>


        </div>
      </div>
    </div>
  </section>
{% endfor %}

templates/includes/scripts.html
  {% load static %}
  
<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>

templates/includes/sidebar.html
<div class="flex-shrink-0 p-3" style="width: 14vw;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-body-emphasis text-decoration-none border-bottom">
      <span class="fs-5 fw-semibold">Здесь будет поиск</span>
    </a>
    <ul class="list-unstyled ps-4">
      <li class="mb-1">
        <button class="btn btn-mycolor btn-toggle d-inline-flex align-items-center rounded border-2 collapsed"
                data-bs-toggle="collapse"
                data-bs-target="#home-collapse"
                aria-expanded="false">
          <i class="fas fa-angle-right mr-2"></i>Home
        </button>
        <div class="collapse" id="home-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li class="mb-2 fs-5 ms-4"><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Overview</a></li>
            <li class="mb-2 fs-5 ms-4"><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Updates</a></li>
            <li class="mb-2 fs-5 ms-4"><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Reports</a></li>
          </ul>
        </div>
      </li>
{#      ==========================================================#}
      <li class="mb-1">
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button"
                id="dropdownMenuButton" data-bs-toggle="dropdown"
                aria-expanded="false">
          <i class="fas fa-angle-right mr-2"></i>
          Dropdown button
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <li><a class="dropdown-item" href="#">Item 1</a></li>
          <li><a class="dropdown-item" href="#">Item 2</a></li>
          <li><a class="dropdown-item" href="#">Item 3</a></li>
        </ul>
      </div>
      </li>
{#      ==========================================================#}
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
          Dashboard
        </button>
        <div class="collapse" id="dashboard-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Overview</a></li>
            <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Weekly</a></li>
            <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Monthly</a></li>
            <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Annually</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
          Orders
        </button>
        <div class="collapse" id="orders-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">New</a></li>
            <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Processed</a></li>
            <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Shipped</a></li>
            <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Returned</a></li>
          </ul>
        </div>
      </li>
      <li class="border-top my-3"></li>
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">New...</a></li>
            <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Profile</a></li>
            <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Settings</a></li>
            <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Sign out</a></li>
          </ul>
        </div>
      </li>
    </ul>
  </div>

templates/webnews/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<header class="header-2">
  <div class="page-header min-vh-100 relative">
    <div class="container">
      <div class="row">
        <div class="col-lg-10 mt-0 mb-7 text-center mx-auto">
          {% block news %}
            {% include 'webnews/news.html' %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}



{% block javascripts %}

<script type="text/javascript">

  if (document.getElementById('state1')) {
    const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
    if (!countUp.error) {
      countUp.start();
    } else {
      console.error(countUp.error);
    }
  }
  if (document.getElementById('state2')) {
    const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
    if (!countUp1.error) {
      countUp1.start();
    } else {
      console.error(countUp1.error);
    }
  }
  if (document.getElementById('state3')) {
    const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
    if (!countUp2.error) {
      countUp2.start();
    } else {
      console.error(countUp2.error);
    };
  }
</script>

{% endblock javascripts %}

templates/webnews/news.html
{% for news in news_list %}
  <section class="pt-1">
    <div class="container">
      <div class="row">
        <div
            class="col-lg-10 z-index-2 border-radius-xl mt-2 mx-auto py-3 blur shadow-blur">
          <h4 style="text-align: left" class="mt-2"><a
              href="{% url 'webnews:newspaper-detail' pk=news.id %}">{{ news.title }}</a></h4>

          <p style="text-align: left">{{ news.context }}</p>


          <p style="text-align: right" class="mt-0 text-black-50">
            {{ news.published_date }}
          </p>
          <p style="text-align: right" class="mt-0 mb-0 text-primary">
            <a href="{% url 'webnews:newspaper-detail' pk=news.id %}">Read more..</a>.
          </p>


        </div>
      </div>
    </div>
  </section>
{% endfor %}

templates/webnews/newspaper_detail.html
{% extends "base.html" %}

{% block content %}

    <section class="pt-1">
    <div class="container">
      <div class="row">
        <div
            class="col-lg-15 z-index-2 border-radius-xl mt-0 mx-auto py-3 blur shadow-blur">
              <h2>
                {{ newspaper.title }}
              </h2>

              {{ newspaper.context }}
                      <hr>
          <p style="text-align: right" class="mt-0 text-black-50">
            {{ newspaper.published_date }}
          </p>
        <div class="d-flex justify-content-between">
        <span>
          <a href="#" onclick="history.back()" class="btn btn-sm bg-gradient-faded-primary-vertical  btn-instagram mb-0 me-1 mt-2 mt-md-0">Previous page</a>
        </span>
        <span>Authors:
            {% for publisher in newspaper.publishers.all %}
              <a href="#" class="border-radius-md">{{ publisher.username }}</a>
              {% if not loop.last %}•{% endif %}
            {% endfor %}</span>
        </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/webnews/redactor_list.html
{% extends "base.html" %}
{% block content %}
  <section class="pt-1">
    <div class="container">
      <div class="row">
        <div
            class="col-lg-13 z-index-2 border-radius-xl mt-2 mx-auto py-3 blur shadow-blur">
          <h2>Redactors:</h2>
          {% for redactor in redactor_list %}
            <section class="pt-1">
              <div class="container">
                <div class="row">
                  <div
                      class="col-lg-10 z-index-2 border-radius-xl mt-2 mx-auto py-3 blur shadow-blur">
                    <div class="d-flex justify-content-between">
        <span>
          <h4 style="text-align: left" class="mt-2"><a
              href="#">{{ redactor.username }}</a></h4>
        </span>
                      <span>
          <p style="text-align: left; font-size: 22px">{{ redactor.first_name }} {{ redactor.last_name }}</p>
        </span>
                    </div>


                    <p>e-mail: {% if redactor.email %}
                      {{ redactor.email }}
                    {% else %}
                      -
                    {% endif %} </p>
                    <p>Years of
                      experience: {{ redactor.years_of_experience }}</p>
                    <p>Joined: {{ redactor.date_joined }}</p>

                  </div>
                </div>
              </div>
            </section>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>

{% endblock %}